// Code generated by goctl. DO NOT EDIT.
package types

type Pagination struct {
	Page     int   `json:"page"`
	PageSize int   `json:"pageSize"`
	Total    int64 `json:"total"`
}

type NoneRes struct {
}

type LoginReq struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type LoginRes struct {
	Info         interface{} `json:"info"`
	AccessToken  string      `json:"accessToken"`
	AccessExpire int64       `json:"accessExpire"`
	RefreshAfter int64       `json:"refreshAfter"`
}

type RegisterReq struct {
	UserName string `json:"username"`
	NickName string `json:"nickname"`
	PassWord string `json:"password"`
	Mobile   string `json:"mobile"`
	IdCard   string `json:"idcard,optional"`
	Email    string `json:"email,optional"`
}

type RegisterRes struct {
	RegisterReq RegisterReq `json:"info"`
}

type GetUserListReq struct {
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
	UserName string `json:"username,optional"`
	NickName string `json:"nickname,optional"`
	PassWord string `json:"password,optional"`
	Mobile   string `json:"mobile,optional"`
	IdCard   string `json:"idcard,optional"`
	Email    string `json:"email,optional"`
}

type GetUserListRes struct {
	Info interface{} `json:"info"`
	Pagination
}

type DeleteUserReq struct {
	Id uint `path:"id"`
}

type UpdateReq struct {
	Id       uint   `json:"id"`
	UserName string `json:"username,optional"`
	NickName string `json:"nickname,optional"`
	PassWord string `json:"password,optional"`
	Mobile   string `json:"mobile,optional"`
	IdCard   string `json:"idcard,optional"`
	Email    string `json:"email,optional"`
}

type GetUserByIdReq struct {
	Id uint `path:"id"`
}

type GetUserByIdRes struct {
	Data interface{} `json:"info"`
}
