// Code generated by goctl. DO NOT EDIT.
package types

type HealthReq struct {
	Ping string `json:"ping,optional"`
}

type HealthRes struct {
	Pong string `json:"pong"`
}

type LoginReq struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type LoginRes struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type RegisterRes struct {
	Id int64 `json:"id"`
	RegisterReq
}
